### ISSUE TITLE
Wish: Going to previous tab via hotkey

### ISSUE THREAD

**Issue by Andreas123456** [kvichans/cuda_ext#20]
I would like to be able to go back to the previous tab via a hotkey. Suppose there are four tabs: [1], [2], [3], [4], and the user activates [1], then [2], then [4], and then presses the hotkey ==> [2] should become active. When the user presses the hotkey again ==> [4] should become active. When the user presses the hotkey again ==> [2] should become active. And so on.

In SynWrite, Ctrl+Tab has the desired behaviour. But note that I don't need the dialog as in SynWrite. Simply going back to the previous tab (without a dialog) would be sufficient.

This feature would be be very useful in conjunction with the new Find in Files feature, because it would make possible to switch back and forth between the search results and the source code tabs in a quick and easy manner.

**Comment by kvichans** [comment]
I need to go back with visit history too. 
I will try to do this

**Comment by Alexey-T** [comment]
done pch. #21 #22 #23

**Comment by kvichans** [comment]
ok
New version is published

**Comment by Alexey-T** [comment]
Needed #24

**Comment by kvichans** [comment]
Fix

**Comment by Andreas123456** [comment]
Great! This is very useful! Thank you very much!

It seems to be impossible to assign Ctrl+Tab as a hotkey to this command. When you try it, Ctrl+Tab will still have the old behaviour. Assigning other keys to the new command works fine. Of course, I can get used to any hotkey sooner or later, but ideally I would like to assign Ctrl+Tab to the new command (Activate previously active tab (go back)).

Thanks again!

**Comment by kvichans** [comment]
Use Go-Back as quick light tool.
Wait a bit. I'm working with another plugin for Go-In-Visit-History

**Comment by Alexey-T** [comment]
It is done, see CudaEx, readme dir, txt file about new goto command
@Andreas123456

**Comment by Andreas123456** [comment]
Yes, I'm using it since quite some time. Thanks again!
